name: The Discerning Dreamer
favicon: null
layout_spectrum: 0.11077
typography_spectrum: 0.73953
title: The Discerning Dreamer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#5c5c5a'
    - '#d3dae4'
    - '#bcbaae'
    - '#7b7871'
  brandStrength: 0.625
  lightness: 0.4620201103389263
  saturation: 0.25
  rhythmicContrast: 0.8443924426101148
purpose: []
