name: The Discerning Dreamer
favicon: null
layout_spectrum: 0.16223377850838006
typography_spectrum: 0.6199224868323654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.821887725032866
  lightness: 0.4620201103389263
  saturation: 0.4577770512551069
  rhythmicContrast: 0.8443924426101148
purpose: []
